version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hab-app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  next-static:
